title: Ziad Ismaili Alaoui
logo: assets/profile2.png
url: "https://www.ziadism.com"
baseurl: "/me"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Theme's Source"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/me/"
 - name: "Contact"
   link: "contact"
