title: Ziad Ismaili Alaoui
logo: assets/profile2.png
#description: 
#show_downloads: true
languages: ["en", "fr"]
theme: jekyll-starter-theme
languages: ["en", "fr", "es"]
defaults:
  - scope:
      path: "en"
    values:
      lang: "en"
  - scope:
      path: "fr"
    values:
      lang: "fr"
